language: ruby
rvm:
  - 1.8.7
  - 1.9.3
before_script:
after_script:
script: "rake spec"
branches:
  only:
    - master
env:
  - PUPPET_VERSION=2.6.2
  - PUPPET_VERSION=2.7.11
  - PUPPET_VERSION=2.7.18
  - PUPPET_VERSION=3.0.1
notifications:
  email: travis@debian-solutions.de
gemfile: .gemfile
